---
# tasks file for suricata-ansible-role

- name: RedHat 7 | Include install tasks
  include_tasks: install-RedHat7.yml
  when: (ansible_distribution == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'CloudLinux') and ansible_distribution_major_version == "7"

- name: RedHat 8 | Include install tasks
  include_tasks: install-RedHat8.yml
  when: (ansible_distribution == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'CloudLinux') and ansible_distribution_major_version == "8"

- name: RedHat 9 | Include install tasks
  include_tasks: install-RedHat9.yml
  when: (ansible_distribution == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'CloudLinux') and ansible_distribution_major_version == "9"

- name: RockyLinux 8 | Include install tasks
  include_tasks: install-RedHat8.yml
  when: ansible_distribution == "Rocky" and ansible_distribution_major_version == "8"

- name: RockyLinux 9 | Include install tasks
  include_tasks: install-RedHat9.yml
  when: ansible_distribution == "Rocky" and ansible_distribution_major_version == "9"

- name: AlmaLinux 8 | Include install tasks
  include_tasks: install-RedHat8.yml
  when: ansible_distribution == "AlmaLinux" and ansible_distribution_major_version == "8"

- name: AlmaLinux 9 | Include install tasks
  include_tasks: install-RedHat9.yml
  when: ansible_distribution == "AlmaLinux" and ansible_distribution_major_version == "9"

- name: Debian | Include install tasks
  include_tasks: install-Debian.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Linux | Include customize tasks
  include_tasks: customize-Linux.yml
  when: ansible_os_family != "Windows" and ansible_os_family != "Debian"

- name: Debian | Include customize tasks
  include_tasks: customize-Debian.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
